### ISSUE TITLE
exception happen

### ISSUE THREAD

**Issue by difeijin** [lequal/sonar-cnes-report#87] opened 2019-09-27 07:14 UTC
### Steps to reproduce behavior
:\Users\peter\Downloads>java -jar sonar-cnes-report-3.1.0.jar -t 34ff2992bfa6f79a5118fa6297c15a8c514c23d4 -s http://192.168.1.240:9000 -p  xxxx
SonarQube URL: http://192.168.1.240:9000
SonarQube online: true
Detected SonarQube version: 7.9.1
Exception in thread "main" java.lang.NumberFormatException: For input string: "AboveAverage.cs"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at java.lang.Double.valueOf(Unknown Source)
        at fr.cnes.sonar.report.providers.ComponentProvider.getMinMetric(ComponentProvider.java:87)
        at fr.cnes.sonar.report.providers.ComponentProvider.getMetricStats(ComponentProvider.java:125)
        at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:101)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:134)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:77)

### Detection version
3.1.0    with sonaqube version 7.9.1

**Comment by begarco** [comment] 2019-09-27 07:54
Duplicate of #86

**Closed by begarco** 2019-09-27 07:54 UTC
