### ISSUE TITLE
NullPointerException when generating the report

### ISSUE THREAD

**Issue by margaale** [lequal/sonar-cnes-report#76] opened 2019-08-22 13:38 UTC
### Expected behavior
Generate the report
### Actual behavior
{
"errors": [
{
"msg": "An error has occurred. Please contact your administrator"
}
]
}
### Steps to reproduce behavior
I'm using docker with 7.9 LTS sonarqube, after selecting the project and clicking the generate button i get that api response instead of the file.
### Detection version
3.0.0 plugin mode

**Comment by louisjdmartin** [comment] 2019-08-22 13:52
Hello,

cnes-report was tested on SonarQube 7.9LTS, it's possible that it came from a configuration that differ from us, can you send me logs generated by Sonar when bug happens ? It should be located at `/opt/sonar/logs/sonar.log`. 

If sonar run through Docker you can execute `docker logs <sonarqube>` to get logs.

Thanks

**Comment by margaale** [comment] 2019-08-22 14:06
Aug 22, 2019 2:04:26 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: http://localhost:9000
Aug 22, 2019 2:04:26 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Aug 22, 2019 2:04:26 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.1
2019.08.22 14:04:40 ERROR web[AWy5nOOkJdn1IFv1AACA][o.s.s.w.WebServiceEngine] Fail to process request http://******************/api/cnesreport/report?key=DenunciaService&author=Administrator&token=a97f1ead53bd5b274b99fd346b96626ee5f87c6a&generation=Generate
java.lang.NullPointerException: null
        at fr.cnes.sonar.report.exporters.docx.RuleComparator.compare(DataAdapter.java:686)
        at fr.cnes.sonar.report.exporters.docx.RuleComparator.compare(DataAdapter.java:674)
        at java.base/java.util.TreeMap.compare(Unknown Source)
        at java.base/java.util.TreeMap.put(Unknown Source)
        at java.base/java.util.AbstractMap.putAll(Unknown Source)
        at java.base/java.util.TreeMap.putAll(Unknown Source)
        at fr.cnes.sonar.report.exporters.docx.DataAdapter.getIssues(DataAdapter.java:348)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:122)
        at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:98)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:133)
        at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:78)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by louisjdmartin** [comment] 2019-08-22 14:39
Thanks for your logs.

It looks like the bug came from the cnes report, not from your configuration.

I will try to release a fix as soon as possible.

For now can you test this branch: `FIXnullpointer`
```
git clone https://github.com/lequal/sonar-cnes-report.git
cd sonar-cnes-report
git checkout FIXnullpointer
mvn package #WARNING: some tests can fails if a sonarqube is running in localhost (some case test network errors)
```

Jar file should be in the `target` folder. Can you test with this fix ?
GitHub does not let me send the compiled jar here. If you can't build it I'll try to send you in another way.

Thanks

**Comment by margaale** [comment] 2019-08-22 15:08
Sure, i'm installing maven now...

**Comment by margaale** [comment] 2019-08-22 15:14
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project cnesreport: There are test failures.
[ERROR]
[ERROR] Please refer to /home/desaadmin/sonar-cnes-report/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/desaadmin/sonar-cnes-report && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:/home/desaadmin/.m2/repository/org/jacoco                                                                    /org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/desaadmin/sonar-cnes-report/target/jacoco.exec -jar /home/desaadmin/sonar-cnes-report/target/                                                                    surefire/surefirebooter12709292607794703493.jar /home/desaadmin/sonar-cnes-report/target/surefire 2019-08-22T12-12-58_994-jvmRun1 surefire13227860691335322921tmp suref                                                                    ire_02725595737273684419tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/desaadmin/sonar-cnes-report && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:/home/desaadmin/.m2/repository/org/jacoco                                                                    /org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/desaadmin/sonar-cnes-report/target/jacoco.exec -jar /home/desaadmin/sonar-cnes-report/target/                                                                    surefire/surefirebooter12709292607794703493.jar /home/desaadmin/sonar-cnes-report/target/surefire 2019-08-22T12-12-58_994-jvmRun1 surefire13227860691335322921tmp suref                                                                    ire_02725595737273684419tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

I got this when building the pluging

**Comment by louisjdmartin** [comment] 2019-08-23 07:09
It should work with the latest Maven.

I've build the project and create a pre-release, you can dowload compiled jar here: https://github.com/lequal/sonar-cnes-report/releases/tag/3.0.1-dev

Can you tell me if it works ?

**Comment by louisjdmartin** [comment] 2019-08-23 11:32
We succeed to reproduce the issue on our system.

The patch has been writed and will be released later this day.

Thanks for your help. 
Once released, feel free to re-open issue or create a new one if report generation fail again with sonar-cnes-report 3.0.1.

**Comment by margaale** [comment] 2019-08-23 11:53
Sorry, i'm from argentina and just got to work, gonna try it now.

Thanks for your help

**Comment by margaale** [comment] 2019-08-23 12:09
Just tried it, it doesn't even show the screen with the project selection in which you generate the report. It shows a Jquery error in the console saying $ is not defined

**Closed** 2019-08-23 12:21 UTC
Labels: bug

**Comment by louisjdmartin** [comment] 2019-08-23 12:26
The web interface has not been modified, it should work.

With 2.2.0 version it's normal to experience this bug, it was fixed in 3.0.0.


Can you test with the new release ?

https://github.com/lequal/sonar-cnes-report/releases/tag/3.0.1

**Comment by margaale** [comment] 2019-08-23 12:33
Thanks, its working fine now (i guess, since i've never have used your plugin before) :-P

**Comment by louisjdmartin** [comment] 2019-08-23 12:35
Perfect !
Thanks for raising this issue.
